replicator:
  reader:
    protocol: grpc
    connectionString: "esdb://localhost:2114?tls=false"
    pageSize: 100

  sink:
    protocol: tcp
    connectionString: "ConnectTo=tcp://admin:changeit@localhost:11131;HeartBeatTimeout=60000;HeartBeatInterval=5000;UseSslConnection=false"
    partitionCount: 1
    bufferSize: 100

  transform:
    type: http
    config: "http://localhost:3000"
    bufferSize: 1

  checkpoint:
    type: file
    path: "/tmp/replicator-checkpoint"
    checkpointAfter: 10

  filters: []

  runContinuously: true
  restartOnFailure: true
  restartDelay: 00:00:05

Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Information
      System: Information
  WriteTo:
    - Name: Console
      Args:
        outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}"
    - Name: File
      Args:
        path: "/tmp/replicator-.log"
        rollingInterval: Day
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
